/*
A KBase module: kb_deseq
*/

module kb_deseq {

    /* A boolean - 0 for false, 1 for true.
        @range (0, 1)
    */
    typedef int boolean;

    /* An X/Y/Z style reference
    */
    typedef string obj_ref;

    typedef structure {
        string        group_name1;
        list<string>  expr_ids1;
        string        group_name2;
        list<string>  expr_ids2;
    } ExperimentGroupIDsList;

    /*
      required params:
      expressionset_ref: ExpressionSet object reference
      diff_expression_obj_name: RNASeqDifferetialExpression object name
      filtered_expression_matrix_name: name of output object filtered expression matrix
      workspace_name: the name of the workspace it gets saved to

      optional params:
      fold_scale_type: one of ["linear", "log2+1", "log10+1"]
      alpha_cutoff: q value cutoff
      fold_change_cutoff: fold change cutoff
    */
    typedef structure{
        obj_ref expressionset_ref;
        string diff_expression_obj_name;
        string filtered_expression_matrix_name;
        string workspace_name;

        int num_threads;
        ExperimentGroupIDsList expr_ids_list;      
        string fold_scale_type;
        float alpha_cutoff;
        float fold_change_cutoff;
    } DESeqInput;

    /*
        result_directory: folder path that holds all files generated by run_deseq2_app
        diff_expression_obj_ref: generated RNASeqDifferetialExpression object reference
        filtered_expression_matrix_ref: generated ExpressionMatrix object reference
        report_name: report name generated by KBaseReport
        report_ref: report reference generated by KBaseReport
    */
    typedef structure{
        string result_directory;
        obj_ref diff_expression_obj_ref;
        obj_ref filtered_expression_matrix_ref;
        string report_name;
        string report_ref;
    }DESeqResult;

    /*  
        run_deseq2_app: run DESeq2 app

        ref: https://www.bioconductor.org/packages/release/bioc/vignettes/DESeq2/inst/doc/DESeq2.html
    */
    funcdef run_deseq2_app(DESeqInput params)
        returns (DESeqResult returnVal) authentication required;
};
